common: &common
  adapter: postgresql
  username: secret_santa
  password: bf883180ad8482b91726f773cbd6d7db # from psql setup, see Postgresql

development:
  <<: *common
  database: secret_santa_development

test:
  <<: *common
  database: secret_santa_test

production:
  <<: *common
  database: secret_santa_production